/**
 * Application Permissions
 */
export const PERMISSIONS = {
  CREATE_PROJECTS: 'CREATE_PROJECTS',
  DELETE_PROJECTS: 'DELETE_PROJECTS',
  INVITE_MEMBERS: 'INVITE_MEMBERS',
  MANAGE_BILLING: 'MANAGE_BILLING',
  MANAGE_ANALYTICS: 'MANAGE_ANALYTICS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_AI: 'MANAGE_AI',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  EXPORT_DATA: 'EXPORT_DATA',
  MANAGE_WORKSPACE: 'MANAGE_WORKSPACE',
  MANAGE_PROJECT_MEMBERS: 'MANAGE_PROJECT_MEMBERS',
  MANAGE_TRACKING: 'MANAGE_TRACKING'
};

export const PERMISSION_VALUES = Object.values(PERMISSIONS);
