/**
 * Application Roles
 */
export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  ANALYST: 'ANALYST',
  VIEWER: 'VIEWER',
  WORKSPACE_OWNER: 'WORKSPACE_OWNER',
  WORKSPACE_ADMIN: 'WORKSPACE_ADMIN',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  DEVELOPER: 'DEVELOPER'
};

export const ROLE_VALUES = Object.values(ROLES);
