import mongoose from 'mongoose';

const eventSchema = new mongoose.Schema(
  {
    project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true, index: true },
    workspace: { type: mongoose.Schema.Types.ObjectId, ref: 'Workspace', required: true, index: true },
    
    // Identity
    anonymousId: { type: String, required: true, index: true }, // UUID generated by SDK
    userId: { type: String, index: true, default: null },       // Internal Customer ID if identified
    sessionId: { type: String, index: true, default: null },    // Links to Session model

    // Event Core
    event: { type: String, required: true, index: true },       // e.g. "Page View", "Button Click", "Purchase"
    type: { type: String, enum: ['page', 'screen', 'track', 'identify', 'group', 'alias'], required: true },
    
    // Payload
    properties: { type: Map, of: mongoose.Schema.Types.Mixed, default: {} },
    traits: { type: Map, of: mongoose.Schema.Types.Mixed, default: {} }, // Used mostly for identify events

    // Context & Device (Enriched by SDK & Backend)
    context: {
      userAgent: { type: String },
      ip: { type: String },
      locale: { type: String },
      timezone: { type: String },
      page: {
        url: { type: String },
        path: { type: String },
        referrer: { type: String },
        search: { type: String },
        title: { type: String }
      },
      campaign: { // UTM Parameters
        source: { type: String },
        medium: { type: String },
        name: { type: String },
        term: { type: String },
        content: { type: String }
      },
      device: {
        id: { type: String },
        manufacturer: { type: String },
        model: { type: String },
        name: { type: String },
        type: { type: String }
      },
      os: {
        name: { type: String },
        version: { type: String }
      },
      browser: {
        name: { type: String },
        version: { type: String }
      },
      screen: {
        width: { type: Number },
        height: { type: Number },
        density: { type: Number }
      },
      location: { // Enriched from IP
        country: { type: String },
        city: { type: String },
        region: { type: String },
        latitude: { type: Number },
        longitude: { type: Number }
      },
      library: { // SDK details
        name: { type: String },
        version: { type: String }
      }
    },

    // Timestamps
    timestamp: { type: Date, required: true, index: true },     // When event actually occurred on client
    receivedAt: { type: Date, default: Date.now },              // When backend received it
    processedAt: { type: Date, default: Date.now }              // When pipeline finished
  },
  { timestamps: false } // We use custom timestamps for analytics events
);

// Compound indexes for fast querying
eventSchema.index({ project: 1, event: 1, timestamp: -1 });
eventSchema.index({ project: 1, userId: 1, timestamp: -1 });
eventSchema.index({ project: 1, sessionId: 1, timestamp: 1 });

export const Event = mongoose.model('Event', eventSchema);
