import mongoose from 'mongoose';

// A specific recommendation generated by the AI based on the Insight
const recommendationSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    description: { type: String, required: true },
    priority: { type: String, enum: ['low', 'medium', 'high', 'critical'], default: 'medium' },
    businessImpact: { type: String }, // AI's estimate of why this matters
    confidenceScore: { type: Number, min: 0, max: 100 },
    actionItems: [{ type: String }],
    status: { type: String, enum: ['new', 'accepted', 'rejected', 'implemented'], default: 'new' }
  },
  { timestamps: true }
);

const insightSchema = new mongoose.Schema(
  {
    project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true, index: true },
    workspace: { type: mongoose.Schema.Types.ObjectId, ref: 'Workspace', required: true, index: true },
    
    // Type of insight detected deterministically by the system
    type: { 
      type: String, 
      enum: [
        'Growth Opportunity', 'Conversion Drop', 'Retention Risk', 
        'Feature Adoption Trend', 'Activation Bottleneck', 'Funnel Drop-off', 
        'Performance Regression', 'Unusual Event Spike', 'Churn Risk', 'Positive Trend'
      ], 
      required: true 
    },
    
    // Human-readable summary
    title: { type: String, required: true },
    description: { type: String, required: true },
    
    // The deterministic data that triggered this insight
    sourceMetadata: {
      sourceType: { type: String, enum: ['analytics', 'funnel', 'retention', 'cohort', 'feature'] },
      sourceId: { type: mongoose.Schema.Types.ObjectId }, // e.g. the specific Funnel ID
      metricName: { type: String },
      previousValue: { type: mongoose.Schema.Types.Mixed },
      currentValue: { type: mongoose.Schema.Types.Mixed },
      percentageChange: { type: Number }
    },

    // Recommendations attached by the AI Engine
    recommendations: [recommendationSchema],

    isArchived: { type: Boolean, default: false },
    deletedAt: { type: Date, default: null }
  },
  { timestamps: true }
);

insightSchema.index({ project: 1, type: 1, createdAt: -1 });

export const Insight = mongoose.model('Insight', insightSchema);
